export const input = {
  "first-name": {
    inputtype: "text",
    required: true,
    label: "Firstname",
    placeholder: "Mark",
  },
  "last-name": {
    inputtype: "text",
    required: true,
    label: "Lastname",
    placeholder: "Twain",
  },
  "full-name": {
    inputtype: "text",
    required: true,
    label: "Fullname",
    placeholder: "Mark Twain",
  },
  address: {
    inputtype: "text-area",
    required: true,
    label: "Address",
    placeholder: "Postal address",
  },
  website: {
    inputtype: "text",
    required: false,
    label: "Website",
    placeholder: "https://www.mark-twain.com",
  },
  mobile: {
    inputtype: "text",
    required: true,
    label: "Mobile",
    placeholder: "",
  },
  telephone: {
    inputtype: "text",
    required: true,
    label: "Telephone",
    placeholder: "",
  },
  "linked-in": {
    inputtype: "text",
    required: false,
    label: "Linkedin",
    placeholder: "https://www.linkedin.com/mark-twain",
  },
  facebook: {
    inputtype: "text",
    required: false,
    label: "Facebook",
    placeholder: "https://www.facebook.com/mark-twain",
  },
  email: {
    inputtype: "text",
    required: true,
    label: "Email",
    placeholder: "marktwain@email.com",
  },
  designation: {
    inputtype: "text",
    required: true,
    label: "Designation",
    placeholder: "Software Developer",
  },
  organization: {
    inputtype: "text",
    required: true,
    label: "Organization",
    placeholder: "ABC LTD.",
  },
  location: {
    inputtype: "text",
    required: true,
    label: "Location",
    placeholder: "Organization location",
  },
  "start-year": {
    inputtype: "text",
    required: true,
    label: "Start year",
    placeholder: "",
  },
  "end-year": {
    inputtype: "text",
    required: true,
    label: "End year",
    placeholder: "",
  },
  course: {
    inputtype: "text",
    required: true,
    label: "Course",
    placeholder: "",
  },
  instituition: {
    inputtype: "text",
    required: true,
    label: "Instituition",
    placeholder: "ABC University",
  },
  grade: { inputtype: "text", required: true, label: "Grade", placeholder: "" },
  achievement: {
    inputtype: "text-area",
    required: true,
    label: "Achievement",
    placeholder: "",
  },
  skill: { inputtype: "text", required: true, label: "Skill", placeholder: "" },
  proficiency: {
    inputtype: "range",
    required: true,
    label: "Proficiency",
    placeholder: "",
  },
  language: {
    inputtype: "text",
    required: true,
    label: "Language",
    placeholder: "",
  },
  title: {
    inputtype: "text",
    required: true,
    label: "Title",
    placeholder: "Project title",
  },
  link: {
    inputtype: "text",
    required: false,
    label: "Link",
    placeholder: "Project demo link (if any)",
  },
  description: {
    inputtype: "text-area",
    required: true,
    label: "Description",
    placeholder: "",
  },
  certification: {
    inputtype: "text",
    required: true,
    label: "Certification",
    placeholder: "",
  },
};
