export const input = {
  "first-name": {
    inputtype: "text",
    required: true,
    label: "Firstname",
    placeholder: "Mark",
    pattern: new RegExp(/[\s\S]+/),
    title: "Please fill out this field",
  },
  "last-name": {
    inputtype: "text",
    required: true,
    label: "Lastname",
    placeholder: "Twain",
    pattern: new RegExp(/[\s\S]+/),
    title: "Please fill out this field",
  },
  "full-name": {
    inputtype: "text",
    required: true,
    label: "Fullname",
    placeholder: "Mark Twain",
    pattern: new RegExp(/[\s\S]+/),
    title: "Please fill out this field",
  },
  address: {
    inputtype: "text-area",
    required: true,
    label: "Address",
    placeholder: "Postal address",
    pattern: new RegExp(/[\s\S]+/),
    title: "Please fill out this field",
  },
  website: {
    inputtype: "text",
    required: false,
    label: "Website",
    placeholder: "https://www.mark-twain.com",
    pattern: new RegExp(
      /https?:\/\/(www\.)?[-a-zA-Z0-9@:%._\+~#=]{1,256}\.[a-zA-Z0-9()]{1,6}\b([-a-zA-Z0-9()@:%_\+.~#?&//=]*)/
    ),
    title: "Please enter a valid url",
  },
  mobile: {
    inputtype: "text",
    required: true,
    label: "Mobile",
    placeholder: "",
    pattern: new RegExp(/^([0|\+[0-9]{1,5})?([7-9][0-9]{9})$/),
    title: "Please enter a valid number",
  },
  telephone: {
    inputtype: "text",
    required: true,
    label: "Telephone",
    placeholder: "",
    pattern: new RegExp(/\d{10,}/),
    title: "Please enter a valid number",
  },
  "linked-in": {
    inputtype: "text",
    required: false,
    label: "Linkedin",
    placeholder: "https://www.linkedin.com/mark-twain",
    pattern: new RegExp(
      /https?:\/\/(www\.)?[-a-zA-Z0-9@:%._\+~#=]{1,256}\.[a-zA-Z0-9()]{1,6}\b([-a-zA-Z0-9()@:%_\+.~#?&//=]*)/
    ),
    title: "Please enter a valid url",
  },
  facebook: {
    inputtype: "text",
    required: false,
    label: "Facebook",
    placeholder: "https://www.facebook.com/mark-twain",
    pattern: new RegExp(
      /https?:\/\/(www\.)?[-a-zA-Z0-9@:%._\+~#=]{1,256}\.[a-zA-Z0-9()]{1,6}\b([-a-zA-Z0-9()@:%_\+.~#?&//=]*)/
    ),
    title: "Please enter a valid url",
  },
  email: {
    inputtype: "text",
    required: true,
    label: "Email",
    placeholder: "marktwain@email.com",
    pattern: new RegExp(
      /^[a-zA-Z0-9.!#$%&'*+/=?^_`{|}~-]+@[a-zA-Z0-9-]+(?:\.[a-zA-Z0-9-]+)*$/
    ),
    title: "Please enter a valid email",
  },
  designation: {
    inputtype: "text",
    required: true,
    label: "Designation",
    placeholder: "Software Developer",
    pattern: new RegExp(/[\s\S]+/),
    title: "Please fill out this field",
  },
  organization: {
    inputtype: "text",
    required: true,
    label: "Organization",
    placeholder: "ABC LTD.",
    pattern: new RegExp(/[\s\S]+/),
    title: "Please fill out this field",
  },
  location: {
    inputtype: "text",
    required: true,
    label: "Location",
    placeholder: "Organization location",
    pattern: new RegExp(/[\s\S]+/),
    title: "Please fill out this field",
  },
  "start-year": {
    inputtype: "text",
    required: true,
    label: "Start year",
    placeholder: "",
    pattern: new RegExp(/^(19[5-9]\d|20[0-4]\d|2050)$/),
    title: "Please enter a valid year",
  },
  "end-year": {
    inputtype: "text",
    required: true,
    label: "End year",
    placeholder: "",
    pattern: new RegExp(/^(19[5-9]\d|20[0-4]\d|2050)$/),
    title: "Please enter a valid year",
  },
  course: {
    inputtype: "text",
    required: true,
    label: "Course",
    placeholder: "",
    pattern: new RegExp(/[\s\S]+/),
    title: "Please fill out this field",
  },
  instituition: {
    inputtype: "text",
    required: true,
    label: "Instituition",
    placeholder: "ABC University",
    pattern: new RegExp(/[\s\S]+/),
    title: "Please fill out this field",
  },
  grade: {
    inputtype: "text",
    required: true,
    label: "Grade",
    placeholder: "",
    pattern: new RegExp(/[\s\S]+/),
    title: "Please fill out this field",
  },
  achievement: {
    inputtype: "text-area",
    required: true,
    label: "Achievement",
    placeholder: "",
    pattern: new RegExp(/[\s\S]+/),
    title: "Please fill out this field",
  },
  skill: {
    inputtype: "text",
    required: true,
    label: "Skill",
    placeholder: "",
    pattern: new RegExp(/[\s\S]+/),
    title: "Please fill out this field",
  },
  proficiency: {
    inputtype: "range",
    required: true,
    label: "Proficiency",
    placeholder: "",
    pattern: new RegExp(/[\s\S]+/),
    title: "Please fill out this field",
  },
  language: {
    inputtype: "text",
    required: true,
    label: "Language",
    placeholder: "",
    pattern: new RegExp(/[\s\S]+/),
    title: "Please fill out this field",
  },
  title: {
    inputtype: "text",
    required: true,
    label: "Title",
    placeholder: "Project title",
    pattern: new RegExp(/[\s\S]+/),
    title: "Please fill out this field",
  },
  link: {
    inputtype: "text",
    required: false,
    label: "Link",
    placeholder: "Project demo link (if any)",
    pattern: new RegExp(/[\s\S]+/),
  },
  description: {
    inputtype: "text-area",
    required: true,
    label: "Description",
    placeholder: "",
    pattern: new RegExp(/[\s\S]+/),
    title: "Please fill out this field",
  },
  certification: {
    inputtype: "text",
    required: true,
    label: "Certification",
    placeholder: "",
    pattern: new RegExp(/[\s\S]+/),
    title: "Please fill out this field",
  },
};
